# Generated by Django 5.0.8 on 2026-05-15 12:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_userprofile_amount_paid_userprofile_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
