# Generated by Django 5.0.8 on 2026-05-20 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_item_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='dealer_type',
            field=models.CharField(choices=[('regular', 'Regular Dealer'), ('composite', 'Composite Dealer')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('general', 'General Store'), ('fancy', 'Fancy Shop'), ('readymade', 'Readymade Shop')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('general', 'General Store'), ('fancy', 'Fancy Shop'), ('readymade', 'Readymade Shop')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='billing.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserSelectedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user selected categories',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
