# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_bill_is_pos_bill_shop_bill_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="hsn_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
